### ISSUE TITLE
Issue downloading blobs from Asia regions

### ISSUE THREAD

**Issue by gmerrall** [luxonis/blobconverter#17] opened 2021-07-12 07:32 UTC
or one at least. I ran the basic demo for an Oak-D which required checking out https://github.com/luxonis/depthai.git and running depthai_demo.py after installing dependencies including blobconverter.  This failed downloading the model with the error
```
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://blobconverter.s3.asia-southeast1.amazonaws.com/0a63afdfadf54974f7c890295c9c2b64f493980804133abbe2c0d29227ba1320.blob"
```

The host blobconverter.s3.asia-southeast1.amazonaws.com does not exist. I figured that it's very likely that the S3 buckets haven't been replicated or it's some region/multi-region thing as boto3 tries to automagically determine the closest region to download from. 

The fix is to simply specify the region when creating the boto3 resource in cli/blobconverter/__init__.py  

from
```
bucket = boto3.resource('s3', config=botocore.client.Config(signature_version=botocore.UNSIGNED))\
    .Bucket('blobconverter')
```

to 
```
# region must be pinned to prevent boto3 specifying a bucket/region that doesn't exist
bucket = boto3.resource('s3', 
    region_name = 'us-east-1', 
    config=botocore.client.Config(signature_version=botocore.UNSIGNED))\
    .Bucket('blobconverter')
```

**Comment by VanDavv** [comment] 2021-07-12 14:22
Hi @gmerrall , thanks for reporting this issue!
I introduced a quick fix here, but since I cannot reproduce this issue on my end, could you give it a try and see if it helps? If yes, I'll release this version as `0.0.12`

**Comment by gmerrall** [comment] 2021-07-13 04:54
Unfortunately it doesn't work. That's because the exception is raised against the bucket.download() method. That puts you in a tricky spot as you need to set the region when initialising the bucket object, but you don't know it's wrong until you actually. go to try and download the file.

I brutally tested this by initialising the bucket object as per defaults then modifying __download_from_s3_bucket with a try/except block.

i.e. (pruned)
```
def __download_from_s3_bucket()
  global bucket # required because of scope
  try:
    progress = __S3ProgressPercentage(bucket, key)
    bucket.download_file(key, str(fpath.absolute()), Callback=progress)
 except botocore.exceptions.EndpointConnectionError:
    bucket = boto3.resource('s3', region='us-east-1')
    progress = __S3ProgressPercentage(bucket, key)
    bucket.download_file(key, str(fpath.absolute()), Callback=progress)
```

That's pretty awful. :) 

I think you may have to refactor things to create a method that inits bucket, and does a quick 0 byte or HEAD request for the object and if it fails, reinit bucket with the region added.
That might mean having the blob/key available earlier but from looking at the code, there's no reason you couldn't move initialising bucket into __download_from_s3_bucket() as it's the only place it's used.

The other option is to fix whatever is going on in S3. It's a bit odd IMHO for boto3 to redirect you to a region where the host doesn't exist. 

I'm duty bound to say this doesn't happen on Google Cloud :)

If you'd prefer and don't mind waiting until the weekend I can refactor as described and submit a pr.

**Comment by VanDavv** [comment] 2021-07-13 07:58
@gmerrall thank you for testing it! I did a quick google search and found that the [`head_bucket`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.head_bucket) method can be the best way to check if the bucket exists in the region - and it worked! I was even able to test the bucket initialization error by fixing the region name of the first bucket initialization call to the one you're assigned by default

```

try:
    s3 = boto3.resource('s3', config=botocore.client.Config(signature_version=botocore.UNSIGNED, region_name='asia-southeast1'))
    bucket = s3.Bucket('blobconverter')
    s3.meta.client.head_bucket(Bucket=bucket.name)
except botocore.exceptions.EndpointConnectionError:
    # region must be pinned to prevent boto3 specifying a bucket/region that doesn't exist
    s3 = boto3.resource('s3', config=botocore.client.Config(signature_version=botocore.UNSIGNED), region_name='us-east-1')
    bucket = s3.Bucket('blobconverter')
    s3.meta.client.head_bucket(Bucket=bucket.name)
```

I updated the linked branch and if that resolves the issue on your end I think we're free to merge and release a new version

**Comment by VanDavv** [comment] 2021-07-19 12:23
@gmerrall I merged mentioned PR with the hope that it will resolve your issue. If not, please feel free to reopen

**Closed** 2021-07-19 12:22 UTC
